# Generated by chatGPT.

import numpy as np
from scipy.io import loadmat
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import accuracy_score

# Load the MNIST data
data = loadmat('mnistFull.mat')
X_train = data['X_train'] / 255.0  # Normalize data
X_test = data['X_test'] / 255.0
y_train = data['y_train'].ravel()  # Flatten arrays to fit
y_test = data['y_test'].ravel()

# Transpose X_train and X_test if they are not in the correct shape
if X_train.shape[0] == 784:
    X_train = X_train.T
if X_test.shape[0] == 784:
    X_test = X_test.T

# Initialize the Ridge Classifier with lambda = 0.0001
# pick solver as auto
ridge_classifier = RidgeClassifier(alpha=0.0001, solver='auto', fit_intercept=True)

# Train the classifier
ridge_classifier.fit(X_train, y_train)

# Predict labels for both training and test datasets
train_pred = ridge_classifier.predict(X_train)
test_pred = ridge_classifier.predict(X_test)

# Calculate and print the accuracy rates
train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)

print(f'Training Accuracy: {train_accuracy:.2f}')
print(f'Test Accuracy: {test_accuracy:.2f}')
